package in.ineuron.model;
// Generated 20 Nov 2025, 12:22:45 pm by Hibernate Tools 5.4.33.Final

/**
 * Insurancepolicy generated by hbm2java
 */
public class Insurancepolicy implements java.io.Serializable {

	private Integer policyNo;
	private String company;
	private String policyName;
	private String policyType;
	private Integer tenure;

	public Insurancepolicy() {
	}

	public Insurancepolicy(String company, String policyName, String policyType, Integer tenure) {
		this.company = company;
		this.policyName = policyName;
		this.policyType = policyType;
		this.tenure = tenure;
	}

	public Integer getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(Integer policyNo) {
		this.policyNo = policyNo;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	public Integer getTenure() {
		return this.tenure;
	}

	public void setTenure(Integer tenure) {
		this.tenure = tenure;
	}

}
