package in.ineuron.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// Generated 20 Nov 2025, 12:53:11 pm by Hibernate Tools 6.2.25.Final

/**
 * Insurancepolicy generated by hbm2java
 */
@Entity
@Table(name="insurancepolicy")
public class Insurancepolicy implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer policyNo;
	private String company;
	private String policyName;
	private String policyType;
	private Integer tenure;

	public Insurancepolicy() {
	}

	public Insurancepolicy(String company, String policyName, String policyType, Integer tenure) {
		this.company = company;
		this.policyName = policyName;
		this.policyType = policyType;
		this.tenure = tenure;
	}

	@Override
	public String toString() {
		return "Insurancepolicy [policyNo=" + policyNo + ", company=" + company + ", policyName=" + policyName
				+ ", policyType=" + policyType + ", tenure=" + tenure + "]";
	}

	public Integer getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(Integer policyNo) {
		this.policyNo = policyNo;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	public Integer getTenure() {
		return this.tenure;
	}

	public void setTenure(Integer tenure) {
		this.tenure = tenure;
	}

}
